package com.skat.smev.snils.domain;

/**
 * @author daria.kulaga
 * @since 01.06.2018.
 */
public enum DocType {
    PASSPORT_RF,
    BIRTH_CERTIFICATE,
    DRIVING_LICENSE_RF,
    FOREIGN_PASSPORT,
    INTERNATIONAL_PASSPORT_RF,
    FORM_9_CERTIFICATE,
    MILITARY_PASSPORT,
    PASSPORT_LOSS_CERTIFICATE,
    PFR_IDENTIFICATION_DOCUMENT,
    RELEASE_CERTIFICATE,
    RESIDENCE_PERMIT_RF,
    SAILOR_PASSPORT,
    SOVIET_PASSPORT,
    TEMPORARY_IDENTITY_CARD_RF
}
